# .readthedocs.yaml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    # Generate API .rst files (like you do locally) before Sphinx runs
    pre_build:
      - sphinx-apidoc -o docs/source/ topoptlab topoptlab/legacy --force --no-toc --separate

sphinx:
  configuration: docs/source/conf.py

# Install your package with the "docs" extra (your README suggests it exists)
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs