name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write   # needed only if you commit the badge back; otherwise keep read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install .[tests]
          pip install pytest coverage coverage-badge

      - name: Run tests with coverage
        run: |
          coverage run -m pytest .
          coverage report -m
          coverage xml -o coverage.xml

      - name: Generate SVG badge
        run: |
          coverage-badge -o coverage.svg -f

      - name: Upload artifacts (badge + html report)
        run: |
          coverage html
        # Always upload so you can view/download from the Actions run
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifacts
          path: |
            coverage.svg
            htmlcov/

      # OPTIONAL: auto-commit the badge into the repo (e.g., at project root)
      # Remove this step if you don't want commits from CI.
      - name: Commit badge
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          mv coverage.svg ./
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add coverage.svg
          git commit -m "CI: update coverage badge" || echo "No changes to commit"
          git push
