name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:

  tests:
    name: Tests (fast)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - run: python -m pip install -U pip
      # If you have heavy/optional native deps, keep CI lean:
      - run: pip install .[tests]
      - name: Pytest (exclude slow)
        env:
          TOPOPTLAB_SKIP_HEAVY: "1"
        run: pytest -q -m "not slow" --maxfail=1 --disable-warnings
